(lang dune 3.0)
(using menhir 2.1)
(name credtt)
(generate_opam_files true)

(package
 (name credtt)
 (synopsis "CredTT: A credence-weighted type theory")
 (depends
  (ocaml (>= 4.14))
  (menhir (>= 20220210))
  (dune (>= 3.0))))
