-- This module serves as the root of the `Cred` library.
-- Import modules here that should be built as part of the library.
import Cred.Core.Value
import Cred.Core.Consequence
import Cred.Cond.Admissible
import Cred.Cond.Copula
import Cred.Collapse.ThreeVal
import Cred.Collapse.Hom
import Cred.Congruence.Unit
import Cred.Congruence.Real
import Cred.Bridge.LPK3
import Cred.Bridge.CondBridge
import Cred.Bridge.Compare
import Cred.Bridge.Crisp
import Cred.Bridge.Curry
import Cred.Valuation
import Cred.Update
import Cred.Predicate
import Cred.Fixpoint
import Cred.Threshold
import Cred.Sequent
import Cred.Kernel
import Cred.Foundation.Language
import Cred.Foundation.Semantics
import Cred.Foundation.Laws
import Cred.Foundation.Consequence
import Cred.Foundation.Proof
import Cred.Foundation.Kernel
import Cred.Foundation.Equality
import Cred.Foundation.Quantifier
import Cred.Foundation.Calculus
import Cred.Foundation.Examples
import Cred.Foundation.RuleCode
