-- This module is the root of the `Cred` library.
-- Import modules here that should be built as part of the library.
import Cred.Core.Value
import Cred.Core.Consequence
import Cred.Cond.Admissible
import Cred.Cond.Proof
import Cred.Cond.Copula
import Cred.Collapse.ThreeVal
import Cred.Collapse.Hom
import Cred.Congruence.Unit
import Cred.Congruence.Real
import Cred.Bridge.LPK3
import Cred.Bridge.CondBridge
import Cred.Bridge.Compare
import Cred.Bridge.Crisp
import Cred.Bridge.Curry
import Cred.Valuation
import Cred.Update
import Cred.Predicate
import Cred.Fixpoint
import Cred.Threshold
import Cred.Sequent
import Cred.Kernel
import Cred.Foundation.Language
import Cred.Foundation.Semantics
import Cred.Foundation.Laws
import Cred.Foundation.Consequence
import Cred.Foundation.Proof
import Cred.Foundation.Kernel
import Cred.Foundation.Equality
import Cred.Foundation.Quantifier
import Cred.Foundation.Calculus
import Cred.Foundation.RuleCode
import Cred.Foundation.Checker
import Cred.Foundation.CheckerSoundness
import Cred.Foundation.Certificate
import Cred.Foundation.Serialization
import Cred.Foundation.Examples
import Cred.Foundation.CertificateExamples
import Cred.Set.Basic
import Cred.Reductio
import Cred.Bridge.CondBridgeIff
import Cred.Set.Russell
import Cred.Bridge.CurryObject
import Cred.Value.BiCredence
import Cred.Set.Classical
import Cred.Set.Quine
import Cred.Reflection
import Cred.Foundation.Diagonal
import Cred.Foundation.CodingNat
import Cred.Set.Separation
import Cred.Branch.Independence
import Cred.Foundation.CertificateBuilder
import Cred.Branch.AxiomAudit
import Cred.Foundation.ProvabilityDeriv
import Cred.Foundation.Arithmetic
import Cred.ToyModel
import Cred.Commitment
import Cred.Cromwell
import Cred.CrossingOut
import Cred.ReflectionTower
import Cred.SeededSystem
import Cred.Lindley
import Cred.Algebra
import Cred.Coherence
import Cred.SelfValidation
import Cred.MetaBootstrap
import Cred.MinimalKernel
import Cred.Completeness
import Cred.CutElim
import Cred.Set.Examples
import Cred.Extraction
import Cred.Foundation.CheckBool
import Cred.Algebra.Finite
import Cred.Algebra.Rational
import Cred.Algebra.Completion
import Cred.SelfRep
import Cred.Foundation.Reflect
import Cred.Foundation.CodeChecker
import Cred.Foundation.Representability
import Cred.Foundation.SigmaOne
import Cred.Foundation.Pairing
import Cred.Foundation.SeqCoding
import Cred.Foundation.Beta
import Cred.Foundation.TreeRepr
import Cred.Approx.Structure
import Cred.Approx.Positivity
import Cred.Approx.Simplex
import Cred.Approx.Monotonicity
import Cred.Approx.MaxPrinciple
import Cred.Approx.NormCircle
import Cred.Approx.Invariant
import Cred.Approx.FirstIntegral
import Cred.Approx.Score
import Cred.Approx.Symplectic
import Cred.Approx.FiniteVolume
import Cred.Approx.DivFree
import Cred.Approx.LieGroup
import Cred.Approx.SSP
import Cred.Approx.Persistence
import Cred.Approx.Compatible
import Cred.Approx.EnergyBalance
import Cred.Approx.Variational
import Cred.Topology.Basic
import Cred.Topology.Clopen
import Cred.Topology.Graded
import Cred.Topology.Threshold
import Cred.Topology.Fuzzy
import Cred.Math.Nat
import Cred.Math.Reals
import Cred.Math.Metric
import Cred.Math.Robustness
import Cred.Dependence.Context
import Cred.Dependence.Conditioning
import Cred.Dependence.RobustCollapse
import Cred.ProofTheory.Labels
import Cred.ProofTheory.Generative
import Cred.ProofTheory.GenerativeQuant
import Cred.ProofTheory.Provenance
import Cred.ProofTheory.Branches
import Cred.Math.Parity
import Cred.Math.Divisibility
import Cred.Examples.FiniteWorlds
import Cred.Examples.RobustCollapse
import Cred.Examples.RobustConditioning
import Cred.Examples.ProofProvenance
import Cred.Examples.Branches
import Cred.Examples.Sqrt2Branch
import Cred.Examples.Elegant
import Cred.Dependence.Network
import Cred.ProofTheory.FoundationProvenance
import Cred.ProofTheory.TheoryBranch
import Cred.Math.Order
import Cred.Examples.MathSeed
