-- This module is the root of the `Cred` library.
-- Import modules here that should be built as part of the library.
import Cred.Core.Value
import Cred.Core.Consequence
import Cred.Cond.Admissible
import Cred.Cond.Copula
import Cred.Collapse.ThreeVal
import Cred.Collapse.Hom
import Cred.Congruence.Unit
import Cred.Congruence.Real
import Cred.Bridge.LPK3
import Cred.Bridge.CondBridge
import Cred.Bridge.Compare
import Cred.Bridge.Crisp
import Cred.Bridge.Curry
import Cred.Valuation
import Cred.Update
import Cred.Predicate
import Cred.Fixpoint
import Cred.Threshold
import Cred.Sequent
import Cred.Kernel
import Cred.Foundation.Language
import Cred.Foundation.Semantics
import Cred.Foundation.Laws
import Cred.Foundation.Consequence
import Cred.Foundation.Proof
import Cred.Foundation.Kernel
import Cred.Foundation.Equality
import Cred.Foundation.Quantifier
import Cred.Foundation.Calculus
import Cred.Foundation.RuleCode
import Cred.Foundation.Checker
import Cred.Foundation.CheckerSoundness
import Cred.Foundation.Certificate
import Cred.Foundation.Serialization
import Cred.Foundation.Examples
import Cred.Foundation.CertificateExamples
import Cred.Set.Basic
import Cred.Reductio
import Cred.Bridge.CondBridgeIff
import Cred.Set.Russell
import Cred.Bridge.CurryObject
import Cred.Value.BiCredence
import Cred.Set.Classical
import Cred.Set.Quine
import Cred.Reflection
import Cred.Foundation.Diagonal
import Cred.Foundation.CodingNat
import Cred.Set.Separation
import Cred.Branch.Independence
import Cred.Foundation.CertificateBuilder
import Cred.Branch.AxiomAudit
import Cred.Foundation.ProvabilityDeriv
import Cred.Foundation.Arithmetic
